### ISSUE TITLE
How to add custom svg icon from local file

### ISSUE THREAD

**Issue by excellencemichel** [octavenz/wagtailextraicons#11]
I followed the procedure described in the readme on how to add custom icons but it doesn't work I don't know how to do it then I really need for a project where customization is needed with icons

**Comment by pjho** [comment]
Hi. I explained to you in https://github.com/octavenz/wagtailextraicons/issues/10 that what you are trying to do is not supported by this library. The note in the readme is about contributing icons to this repo.

If you are using wagtail 2.15 or greater then adding svg icons is easy. I wrote instructions in your preveious issue.

If you are using an older version of wagtail then adding icons is not easy at all because it uses an icon font system. So you need to generate a font file and add some css to do that.
